name: aircharge
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  page_transition: ^2.1.0
  dots_indicator: ^3.0.0
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.5.0
  get:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

# To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
 
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: hero
      fonts:
        - asset: assets/fonts/Hero/Hero-Regular.ttf
          weight: 700
        - asset: assets/fonts/Hero/Hero-Regular.otf
          weight: 400

    - family: meta
      fonts:
        - asset: assets/fonts/Meta/Meta-Normal-Font.otf
          weight: 700
        - asset: assets/fonts/Meta/Meta-Normal-Font.otf
          weight: 400
        - asset: assets/fonts/Meta/Meta-Normal-Font.otf
          weight: 600  